; Generated by Auto-GUI 3.0.0
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

CustomColor =  White ;FF00FF
opacity = 255
opacityPercent = 50

Gui +AlwaysOnTop +LastFound
WinSet, Transparent,%opacity% 
Gui Color, %CustomColor%
Gui Font, s9, Segoe UI
Gui Add, GroupBox, x7 y7 w424 h394 +Center, POE小幫手127
Gui Add, Button, gReply()       x21  y25  w130 h36, 自動回覆：稍等
Gui Add, Button, gInvite()      x21  y71  w130 h36, 邀請組隊
Gui Add, Button, gHideout()     x21  y117 w130 h36, 回藏身處
Gui Add, Button, gAfk()         x21  y163 w130 h36, AFK
Gui Add, Button, gTrade()       x21  y209 w130 h36, 交易
Gui Add, Button, gThanks()      x21  y255 w130 h36, 自動回覆：感謝
Gui Add, Button, gFastLogOut()  x21  y301 w130 h36, 快速登出
Gui Add, Button, gOosCommand()  x21  y347 w130 h36, OOS
Gui Add, Button, gSubmit()      x310 y301 w100 h36 , 編輯熱鍵
Gui Add, Slider, vSldr gopacity x300 y352 w120 h32, %opacity%
Gui Add, Hotkey, vSetReply gHotReply()            x174 y31  w98 h21,F4
Gui Add, Hotkey, vSetInvite gHotInvite()          x173 y77  w98 h21,Numpad7
Gui Add, Hotkey, vSetHideout gHotHideout()        x174 y123 w98 h21,F11
Gui Add, Hotkey, vSetAfk gHotAfk()                x174 y169 w98 h21,F9
Gui Add, Hotkey, vSetTrade gHotTrade()            x174 y215 w98 h21,Numpad8
Gui Add, Hotkey, vSetThanks gHotThanks()          x174 y261 w98 h21,Numpad9
Gui Add, Hotkey, vSetFastLogOut gHotFastLogOut()  x174 y307 w98 h21,F5
Gui Add, Hotkey, vSetOosCommand gHotOosCommand()  x174 y353 w98 h21,F2

isEnabled = False
Submit():
{
    GuiControlGet, isEnabled, Enabled,msctls_hotkey321
    if(isEnabled == 1){
        GuiControl, Disable, msctls_hotkey321
        GuiControl, Disable, msctls_hotkey322
        GuiControl, Disable, msctls_hotkey323
        GuiControl, Disable, msctls_hotkey324
        GuiControl, Disable, msctls_hotkey325
        GuiControl, Disable, msctls_hotkey326
        GuiControl, Disable, msctls_hotkey327
        GuiControl, Disable, msctls_hotkey328
    }else{
        GuiControl, Enable, msctls_hotkey321
        GuiControl, Enable, msctls_hotkey322
        GuiControl, Enable, msctls_hotkey323
        GuiControl, Enable, msctls_hotkey324
        GuiControl, Enable, msctls_hotkey325
        GuiControl, Enable, msctls_hotkey326
        GuiControl, Enable, msctls_hotkey327
        GuiControl, Enable, msctls_hotkey328        
    }    
}

HotReply(): 
{
    Gui Submit 
    Hotkey, %SetReply%, Reply()
}

HotInvite(): 
{
    Gui Submit 
    Hotkey, %SetInvite%, Invite()
}
HotHideout():
{
    Gui Submit 
    Hotkey, %SetHideout%, Hideout()
}

HotAfk():
{
    Gui Submit 
    Hotkey, %SetAfk%, Afk()
}



HotTrade():
{
    Gui Submit 
    Hotkey, %SetTrade%, Trade()  
}


HotThanks():
{
    Gui Submit 
    Hotkey, %SetThanks%, Thanks()
}


HotFastLogOut(): 
{
    Gui Submit 
    Hotkey, %SetFastLogOut%, FastLogOut()
}


HotOosCommand():
{
    Gui Submit 
    Hotkey, %SetOosCommand%, OosCommand()    
}

Gui Show, w439 h409, POE小幫手-127
Return

opacity:
opacity := round(((sldr*255)/100))+30
Winset Transparent, %opacity%
Return

getarr(x){
    Array :={"Tra": "/交易 ", "Log": "/exit", "Oos": "/oos", "Afk": "/afk", "Hid": "/hideout", "Rem": "/剩餘怪物", "Inv": "/邀請 ", "Thx": "謝謝尼", "Wait": "稍等喔~"}
    Return % Array[x]
}

Copy(y){
    BlockInput On
    clipboard_save := clipboard
    clipboard:=
    clipboard:= % getarr(y)
    ClipWait
    Send ^v
    Sleep 2
    clipboard = %clipboard_save%
    BlockInput Off
}

Thanks():
Thanks()
return

Thanks(){
    WinActivate Path of Exile
	Send ^{Enter}
	Send % Copy("Thx")
	Send {Enter}
    Return
}

Trade():
Trade()
Return

Trade(){
    WinActivate Path of Exile
    BlockInput On
    Send ^{Enter}
    Send {Home}
    Send {Delete}
    Send % Copy("Tra")
    Send {Enter}
    BlockInput Off
    return
}


Invite():
Invite()
Return

Invite(){
    WinActivate Path of Exile
    BlockInput On
    Send ^{Enter}
    Send {Home}
    Send {Delete}
    Send % Copy("Inv")
    Send {Enter}
    BlockInput Off
    return
}

Reply():
Reply()
Return
Reply(){
    WinActivate Path of Exile
    BlockInput On
    Send ^{Enter}
    Send % Copy("Wait")
    Send {Enter}
    BlockInput Off
    return
}

Afk():
Afk()
Return
Afk(){
    WinActivate Path of Exile
    BlockInput On
    Send {Enter}        
    Sleep 2
    Send % Copy("Afk")
    Send {Enter}
    BlockInput Off
    return
}

Hideout():
Hideout()
Return

Hideout(){
        WinActivate Path of Exile
        BlockInput On
        Send {Enter}
        Sleep 2
        Send % Copy("Hid")
        Send {Enter}
        BlockInput Off
        return
}

OosCommand():
OosCommand()
Return
OosCommand(){
        WinActivate Path of Exile
        BlockInput On
        Send {Enter}
        Send % Copy("Oos")
        Send {Enter}
        BlockInput Off
        return
}

FastLogOut():
FastLogOut()
Return
FastLogOut(){
        WinActivate Path of Exile
        BlockInput On
        Send {Enter}
        Sleep 2
        Send % Copy("Log")
        Send {Enter}
        BlockInput Off
        return
}


CheckRemaining():
CheckRemaining()
Return
CheckRemaining(){
        WinActivate Path of Exile
        BlockInput On
        Send {Enter}
        Sleep 2
        Send % Copy("Rem")
        Send {Enter}
        BlockInput Off
        return
}

GuiEscape:
GuiClose:
    ExitApp
